spring:
  application:
    name: talis
  datasource:
    #配置数据库的连接信息
    url: jdbc:mysql://localhost:3306/db07
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  output:
    ansi:
      enabled: always

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

#监听端口
server:
  port: 8080

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: cn-shenzhen-talis
    region: cn-beijing

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


